### ISSUE TITLE
Topology not perserved

### ISSUE THREAD

**Issue by Bibi56** [pnorman/openstreetmap-cartographic#3]
Not an easy topic. The answer may be won't do ;-). It may depends on PostGIS.
https://www.openstreetmap.org/#map=18/47.79839/-3.47620&layers=N
![image](https://user-images.githubusercontent.com/19638211/84824106-b7106080-b01f-11ea-9d9f-194a7b0bcb0b.png)

https://pnorman.dev.openstreetmap.org/cartographic/mapbox-gl.html#16/47.797919/-3.476055
![image](https://user-images.githubusercontent.com/19638211/84824028-9811ce80-b01f-11ea-9a4b-7724a138178a.png)

Overzooming for clarification

**Comment by pnorman** [comment]
It does depend on PostGIS, but we can change settings. However, I don't see a practical problem here. It looks to be off by 1 vector tile unit, which is under 1px, even on high-DPI displays.

Topology isn't an issue because vector tiles don't have topology.
